# Generated by Django 3.2 on 2021-05-30 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='dis',
            new_name='duration',
        ),
    ]
