# Generated by Django 3.2 on 2021-05-30 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0002_rename_dis_restaurant_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='restaurant',
            new_name='restaurants',
        ),
    ]
