# Generated by Django 3.2 on 2021-05-30 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0005_alter_cart_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='items',
            new_name='menu',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='users',
            new_name='user',
        ),
    ]
