# Generated by Django 3.2 on 2021-05-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0006_auto_20210530_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.TextField(null=True),
        ),
    ]
