# Generated by Django 3.2 on 2021-05-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0010_alter_menu_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
