# Generated by Django 3.2 on 2021-06-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0011_cart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='amount',
            field=models.FloatField(null=True),
        ),
    ]
