# Generated by Django 3.2 on 2021-06-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0012_cart_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='amount',
        ),
        migrations.AddField(
            model_name='menu',
            name='amount',
            field=models.FloatField(null=True),
        ),
    ]
