# Generated by Django 3.2 on 2021-06-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0014_alter_order_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
