# Generated by Django 3.2 on 2021-06-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0015_alter_order_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
