# Generated by Django 3.2 on 2021-06-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0022_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='duration',
        ),
        migrations.AddField(
            model_name='menu',
            name='duration',
            field=models.FloatField(null=True),
        ),
    ]
