# Generated by Django 3.2.1 on 2021-06-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0023_auto_20210604_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
    ]
