# Generated by Django 3.2 on 2021-06-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0025_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='amount',
            field=models.FloatField(default='', null=True),
        ),
    ]
