# Generated by Django 3.2 on 2021-06-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0026_alter_menu_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
